name: khatt_1
channels:
  - default
  - conda-forge
dependencies:
  - python=3.7
  - pip=22.0.4
  - matplotlib=3.5.1
  - numpy=1.21.5
  - tensorflow-gpu==1.15.0
  - scipy=1.7.3
  - pip:
    - ds_ctcdecoder== 0.9.3
    - mako==1.2.0
    - pandas==1.3.5
    - protobuf==3.19.4
    - pyyaml==6.0
    - pyxdg==0.27
    - requests==2.27.1
    - tree==0.2.4
    - lang-trans==0.6.0
